services:
  app:
    image: python:3.12-slim-bullseye
    volumes:
      - .:/app
    ports:
      - 3000:3000
    command: bash
    tty: true
  
  db:
    image: postgres:16.8-alpine3.20
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432
